apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  # Template for nodes created by this NodePool
  template:
    metadata:
      # Labels to apply to nodes
      labels:
        provisioner: karpenter
    spec:
      # Requirements for node selection
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - "m5.large"
            - "m5.xlarge"
            - "m5.2xlarge"
            - "c5.large"
            - "c5.xlarge"
            - "c5.2xlarge"
            - "t3.medium"
            - "t3.large"
            - "t3.xlarge"

      # Reference to EC2NodeClass
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

      # Node startup and shutdown behavior
      startupTaints:
        - key: karpenter.sh/unschedulable
          value: "true"
          effect: NoSchedule

  # Disruption settings
  disruption:
    # Consolidation policy
    consolidationPolicy: WhenUnderutilized
    # Time to wait before terminating empty nodes
    consolidateAfter: 30s

  # Limits for this NodePool
  limits:
    cpu: 1000
    memory: 1000Gi
