apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-demo-cluster"
  amiSelectorTerms:
    - alias: "al2023@v20241212"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "demo-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "demo-cluster"
