apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-test-app
  namespace: default
  labels:
    app: karpenter-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karpenter-test
  template:
    metadata:
      labels:
        app: karpenter-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      # This toleration allows the pod to be scheduled on Karpenter nodes
      tolerations:
        - key: karpenter.sh/unschedulable
          operator: Equal
          value: "true"
          effect: NoSchedule
      # Node affinity to prefer Karpenter nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: karpenter.sh/nodepool
                    operator: Exists
