---
apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
  - name: app
    image: nginx:1.14.2
    resources:
      requests:
        memory: 128Mi
        cpu: 500m
      limits:
        memory: 128Mi
        cpu: 500m
---
---
apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
  - name: app
    image: nginx:1.14.2
    resources:
      requests:
        memory: 64Mi
        cpu: 200m
      limits:
        memory: 128Mi
        cpu: 500m
---
apiVersion: v1
kind: Pod
metadata:
  name: burstable-no-limit-pod
spec:
  containers:
  - name: app
    image: nginx:1.14.2
    resources:
      requests:
        memory: 64Mi
        cpu: 200m
---
---
apiVersion: v1
kind: Pod
metadata:
  name: best-effort-pod
spec:
  containers:
  - name: app
    image: nginx:1.14.2
